### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [zhubinsheng/ecdh_aes_base54_md5#1]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by zhubinsheng** [comment]
i will change and reply you tomorrow

**Comment by zhubinsheng** [comment]
ok,I have used the new jar package

**Comment by Neustradamus** [comment]
@zhubinsheng: Always here: https://github.com/zhubinsheng/ecdh_aes_base54_md5/search?q=spongycastle&unscoped_q=spongycastle

**Comment by Neustradamus** [comment]
@zhubinsheng: Any news?

**Comment by zhubinsheng** [comment]
only text, not use ! now i had delete is

**Comment by Neustradamus** [comment]
Now it is Bouncy Castle but you have always this word, please replace to Bouncy Castle.

**Comment by zhubinsheng** [comment]
thankx i had replece all
